### ISSUE TITLE
What Data Types and IPC formats?

### ISSUE THREAD

**Issue by wilhelmagren** [Ignalina/alloy#1]
Should it allow all mutually implemented Data Types? As of writing this, the only exceptions are:
- Float16 & Map, Go implementations but not Rust

"Custom schema metadata" is currently implemented for both languages. 

The C data interface supports schema import/export and array import/export fully in both Go and Rust. Use this for v0.1?

Third party data formats, only CSV and Parquet are supported by both Go and Rust. However, nested read/write is not supported for Parquet files in Rust.

Also, why do you need to transfer data from Go to Rust (and vice versa)? What functionality does Rust offer that Go lacks? Or what need is this potential *bridge* satisfying? I'm just curious.

**Comment by Ignalina** [comment]
Very good points , I start with the easy one.

>>Also, why do you need to transfer data from Go to Rust (and vice versa)? 
Was thinking Alloy would be part of Thund ,An DAG executer ala Airflow based on GO  , where i realise that RUST is growing especially its Arrow implementations .. so would be nice to have "RUST" plugins-steps !

Also .. since i made an interface in the top ... more languages like Javascript etc would be possible ..as long as they have supported Apache Arrow bindings.


....to be continued ...
