### ISSUE TITLE
Wrong Go version in go.mod?

### ISSUE THREAD

**Issue by willeagren** [Ignalina/alloy#24]
"go 1.18" but should be 1.19 right?

Don't know how this impacts things, but could be a reason for the previously failing workflows, since those use the version specified in the go.mod file (i think).

**Comment by willeagren** [comment]
It does not cause the workflows to fail, but, still we might think about updating this to 1.19.1 that we actually want to use.

**Comment by Ignalina** [comment]
Also thinking about that one, yes it seems the ffi stuff started to wok with go 1.19+ .   The go.mod thing says that min level of dependencies aswell as the module itself is 1.18.

https://go.dev/ref/mod

/Mvh Rickard

Skickat från min iPhone

2 okt. 2022 kl. 10:08 skrev Wilhelm Ågren ***@***.***>:

﻿

"go 1.18" but should be 1.19 right?

Don't know how this impacts things, but could be a reason for the previously failing workflows, since those use the version specified in the go.mod file (i think).
