### ISSUE TITLE
Bug on C-dummy-function branch

### ISSUE THREAD

**Issue by wilhelmagren** [Ignalina/alloy#36]
When actually sending an Array with buffers, and a schema, the kernel panics in Rust for the following reason. How do we define the Fields for the schema in Go?

```
CDataInterface("The datatype \"\"F1-i32\"\" is still not supported in Rust implementation")
```

**Comment by willeagren** [comment]
I fixed this by actually following the arrow C data interface specification... (https://arrow.apache.org/docs/format/CDataInterface.html) You have to specify the format string accordingly. 

Now I get new error; and it looks promising. 
```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`: PrimitiveArray data should contain a single buffer only (values buffer)', /home/vance/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-9.1.0/src/array/array_primitive.rs:501:9
```

I think we are close. Will look into the current error. Maybe even push to main.

**Comment by Ignalina** [comment]
Fetching my coffe :) dont finish everthing before my coffe.

This one reminds me of someone :)

https://youtu.be/43VhRKJX_sk



Skickat från min iPhone

6 okt. 2022 kl. 19:52 skrev Wilhelm Ågren ***@***.***>:

﻿

I fixed this by actually following the arrow C data interface specification... (https://arrow.apache.org/docs/format/CDataInterface.html) You have to specify the format string accordingly.

Now I get new error; and it looks promising.

thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`: PrimitiveArray data should contain a single buffer only (values buffer)', /home/vance/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-9.1.0/src/array/array_primitive.rs:501:9


I think we are close. Will look into the current error. Maybe even push to main.

**Comment by willeagren** [comment]
hahaha yes duracell programmer

**Comment by willeagren** [comment]
Don't really know how to solve this. I've downloaded the arrow-rs source code for v9.1.0 and looked at the specific line that causes the kernel panic, but it doesn't name anything about assertions nor `left == right`. It uses std::box things but that also doesn't compare like that. 

However, it might have to do with the RawPtrBox struct,
```
 /// * `ptr` is not aligned to a slice of type `T`. This is guaranteed if it was built from a slice of type `T`.
```

Maybe the offset I am sending is wrong. Will look this up.

**Comment by willeagren** [comment]
```
func (exp *schemaExporter) finish(out *CArrowSchema) {
	out.dictionary = nil
	out.name = C.CString(exp.name)
	out.format = C.CString(exp.format)
	out.metadata = (*C.char)(C.CBytes(exp.metadata))
	out.flags = C.int64_t(exp.flags)
	out.n_children = C.int64_t(len(exp.children))

	if len(exp.children) > 0 {
		children := allocateArrowSchemaArr(len(exp.children))
		childPtrs := allocateArrowSchemaPtrArr(len(exp.children))

		for i, c := range exp.children {
			c.finish(&children[i])
			childPtrs[i] = &children[i]
		}

		out.children = (**CArrowSchema)(unsafe.Pointer(&childPtrs[0]))
	} else {
		out.children = nil
	}

	out.release = (*[0]byte)(C.goReleaseSchema)
}
```

DO THIS later

**Comment by Ignalina** [comment]
Tjena !

Ok du har troligen förklarat detta för mig :) Men "schemat" är datatypen 
per column , enklast tex int32 i enklaste fallet .. Alltså inte det 
schema jag försöker tråckla in som motsvarar en tabll (multipla 
columner) ....

ha ha , men .. å andra sidan har den ju ett fält "struct ArrosSchema ** 
children) som skulle kunna vara column data typerna.

/mvh Rickard


Sidan 180 Matthews bok

"An Interesting Tidbit
Despite the name, the ArrowSchema structure is actually more similar to
the arrow::Field class in the C++ library than the arrow::Schema
class. The C++ Schema class represents a collection of fields (containing a
name, datatype, and potential metadata) and optional schema-level metadata.
By having the ArrowSchema structure more closely resemble the Field
representation, it can serve dual purposes; a full schema is represented 
as the
Struct type whose children are the individual fields of the schema. This
reuse keeps the ABI smaller and requires only the two ArrowSchema and
ArrowArray structures instead of requiring another to represent fields too.



/mvh RIckard
